name = "RheoModels"
uuid = "e43521cb-ed0c-4cef-aa90-e4f5cf94df95"
version = "0.1.0-DEV"
authors = ["Wouter Grouve <wjbgrouve@gmail.com>"]

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
